### ISSUE TITLE
Mobs move in 8 directions

### ISSUE THREAD

**Issue by JonathanLayman** [TensorStudios/RPG#31]
Mobs currently move in all directions, they need to only move in 8 directions to face the player

- Need to research

**Comment by JonathanLayman** [comment]
- Use the A* Method to determine path to take, add in diagonal movement. Based on the mob's center position it will move in the direction the tile recommends using vectors. This may create situations where the mob runs into walls, will need testing to fine tune.
- Mobs should use the same Circle and Square method outlined in #11 to determine if the player is within their range, and then face the player automatically.

**Comment by JonathanLayman** [comment]
Does this still need to happen?

**Comment by Ramrod7942** [comment]
Yeah, haven't gotten to that yet.
